import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/NavBar";
import Container from "@/components/global/Container";
import Providers from "./Providers";
export const metadata: Metadata = {
  title: "NextJS Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Navbar />
          <Container className="py-20">{children}</Container>
        </Providers>
      </body>
    </html>
  );
}
